services:
  texlab:
    image: genjiohara/texlab
    container_name: haskell-ml-texlab
    volumes:
      - ./:${PWD}
    working_dir: ${PWD}
    tty: true
  hls:
    image: genjiohara/haskell-language-server
    container_name: haskell-ml-hls
    volumes:
      - ./:${PWD}
    working_dir: ${PWD}
    tty: true
