services:
  lhaskell:
    image: genjiohara/lhaskell
    container_name: haskell-ml
    volumes:
      - ./:/root/workspace
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/.gitconfig:/root/.gitconfig
      - ~/.ssh:/root/.ssh
    environment:
      - DISPLAY=$DISPLAY
    working_dir: /root/workspace
    tty: true
