name: Build LaTeX document
on:
  push:
permissions:
  contents: write
  pages: write
  id-token: write
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          working_directory: app/
          root_file: Main.lhs
          args: ""
      - name: Prepare deployment files
        run: |
          mkdir -p public
          mv Main.pdf public/
          cat <<EOF > public/index.html
          <!DOCTYPE html>
          <html>
            <head>
              <title>圏論ノート</title>
              <style>
                object,iframe {
                  width: 100vw;
                  height: 100vh;
                }
              </style>
            </head>
            <body>
              <object data="Main.pdf" type="application/pdf" width="100%" height="100%">
                <iframe src="Main.pdf" width="100%" height="100%">
                  This browser does not support PDFs.
                  Please download the PDF to view it: 
                  <a href="Main.pdf">Download PDF</a>
                </iframe>
              </object>
            </body>
          </html>
          EOF
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
